/* Objective: Understand how the const qualifier prevents accidental changes to a variable during program execution.
Instructions:
1. Declare a constant integer: const int rate_limit = 100;.
2. Try to change its value on the next line: rate_limit = 150;.
3. Observe the error generated by the compiler when trying to compile this code.
4. Comment out the forbidden assignment line so that the code compiles again and print the value of rate_limit using printf. */

#include <stdio.h>

int main(void)
{
    const int rate_limit = 100;

    // rate_limit = 150; // Error: cannot modify a const variable

    printf("Rate limit: %d\n", rate_limit);

    return 0;
}